# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: 205930636266.dkr.ecr.us-east-1.amazonaws.com/weather-repo-backend-api
#           ports:
#             - containerPort: 8000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   selector:
#     app: backend
#   ports:
#     - port: 8000
#       targetPort: 8000
#   type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: symantec-ca
data:
  symantec_wss_ca.pem: |
    __SYMANTEC_WSS_CERT__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 205930636266.dkr.ecr.us-east-1.amazonaws.com/weather-repo-backend-api
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: custom-ca
              mountPath: /etc/ssl/certs/symantec_wss_ca.pem
              subPath: symantec_wss_ca.pem
          env:
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/symantec_wss_ca.pem
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/symantec_wss_ca.pem
            - name: HTTPLIB2_CA_CERTS
              value: /etc/ssl/certs/symantec_wss_ca.pem
      volumes:
        - name: custom-ca
          configMap:
            name: symantec-ca
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
